data:extend({
	{
		type = "fluid",
		name = "tbp-fuel-mix",
		subgroup = "uranium-prefluids",
		default_temperature = 25,
		heat_capacity = "1KJ",
		base_color = {r=0, g=0.34, b=0.6},
		flow_color = {r=0.7, g=0.7, b=0.7},
		max_temperature = 100,
		icon = "__bot365-nuclear-fuel-reprocessing__/graphics/icons/uranium_process/TBP.png",
		icon_size = 32,
		pressure_to_speed_ratio = 0.4,
		flow_to_energy_ratio = 0.59,
		order = "a[fluid]-l[tbp]"
	},
	{
		type = "fluid",
		name = "hydroxylamine",
		subgroup = "uranium-prefluids",
		default_temperature = 25,
		heat_capacity = "1KJ",
		base_color = {r=0, g=0.34, b=0.6},
		flow_color = {r=0.7, g=0.7, b=0.7},
		max_temperature = 100,
		icon = "__bot365-nuclear-fuel-reprocessing__/graphics/icons/uranium_process/hydroxylamine.png",
		icon_size = 32,
		pressure_to_speed_ratio = 0.4,
		flow_to_energy_ratio = 0.59,
		order = "a[fluid]-m[hydroxylamine]"
	},
	{
		type = "fluid",
		name = "dilute-nitric-acid",
		subgroup = "uranium-prefluids",
		default_temperature = 25,
		heat_capacity = "1KJ",
		base_color = {r=0, g=0.34, b=0.6},
		flow_color = {r=0.7, g=0.7, b=0.7},
		max_temperature = 100,
		icon = "__bot365-nuclear-fuel-reprocessing__/graphics/icons/uranium_process/dilute-nitric-acid.png",
		icon_size = 32,
		pressure_to_speed_ratio = 0.4,
		flow_to_energy_ratio = 0.59,
		order = "a[fluid]-n[dilute-nitric-acid]"
	},
	{
		type = "fluid",
		name = "uranyl-nitrate",
		subgroup = "uranium-prefluids",
		default_temperature = 25,
		heat_capacity = "1KJ",
		base_color = {r=0.96, g=1, b=0.25},
		flow_color = {r=0.3, g=0.31, b=1},
		max_temperature = 100,
		icon = "__bot365-nuclear-fuel-reprocessing__/graphics/icons/uranium_process/uranyl-nitrate.png",
		icon_size = 32,
		pressure_to_speed_ratio = 0.4,
		flow_to_energy_ratio = 0.59,
		order = "a[fluid]-o[uranyl-nitrate]"
	},
	{
		type = "fluid",
		name = "pu-reductant",
		subgroup = "uranium-prefluids",
		default_temperature = 25,
		heat_capacity = "1KJ",
		base_color = {r=0.29, g=0.53, b=0.53},
		flow_color = {r=0.52, g=0.27, b=0.27},
		max_temperature = 100,
		icon = "__bot365-nuclear-fuel-reprocessing__/graphics/icons/uranium_process/pu-reductant.png",
		icon_size = 32,
		pressure_to_speed_ratio = 0.4,
		flow_to_energy_ratio = 0.59,
		order = "a[fluid]-p[pu-reductant]"
	},
	{
		type = "fluid",
		name = "liquid-spent-fuel",
		subgroup = "uranium-prefluids",
		default_temperature = 25,
		heat_capacity = "1KJ",
		base_color = {r=0.92, g=0.23, b=1},
		flow_color = {r=0.23, g=1, b=0.41},
		max_temperature = 100,
		icon = "__bot365-nuclear-fuel-reprocessing__/graphics/icons/uranium_process/liquid-spent-fuel.png",
		icon_size = 32,
		pressure_to_speed_ratio = 0.4,
		flow_to_energy_ratio = 0.59,
		order = "a[fluid]-q[liquid-spent-fuel]"
	},
		{
		type = "fluid",
		name = "primary-stream",
		subgroup = "uranium-prefluids",
		default_temperature = 25,
		heat_capacity = "1KJ",
		base_color = {r=0.23, g=1, b=0.41},
		flow_color = {r=0.92, g=0.23, b=1},
		max_temperature = 100,
		icon = "__bot365-nuclear-fuel-reprocessing__/graphics/icons/uranium_process/primary-stream.png",
		icon_size = 32,
		pressure_to_speed_ratio = 0.4,
		flow_to_energy_ratio = 0.59,
		order = "a[fluid]-r[primary-stream]"
	},	
	{
		type = "fluid",
		name = "waste-nitric-acid",
		subgroup = "uranium-prefluids",
		default_temperature = 25,
		heat_capacity = "1KJ",
		base_color = {r=1, g=1, b=0.9},
		flow_color = {r=0.6, g=0, b=0.6},
		max_temperature = 100,
		icon = "__bot365-nuclear-fuel-reprocessing__/graphics/icons/uranium_process/waste-nitric-acid.png",
		icon_size = 32,
		pressure_to_speed_ratio = 0.4,
		flow_to_energy_ratio = 0.59,
		order = "a[fluid]-s[waste-nitric-acid]"
	},
	{
		type = "fluid",
		name = "u-tbp",
		subgroup = "uranium-prefluids",
		default_temperature = 25,
		heat_capacity = "1KJ",
		base_color = {r=0.43, g=1, b=0.61},
		flow_color = {r=1, g=0.1, b=0.3},
		max_temperature = 100,
		icon = "__bot365-nuclear-fuel-reprocessing__/graphics/icons/uranium_process/UTPB.png",
		icon_size = 32,
		pressure_to_speed_ratio = 0.4,
		flow_to_energy_ratio = 0.59,
		order = "a[fluid]-t[u-tbp]"
	},
	{
		type = "fluid",
		name = "pu-aqueous",
		subgroup = "uranium-prefluids",
		default_temperature = 25,
		heat_capacity = "1KJ",
		base_color = {r=1, g=0.2, b=0.71},
		flow_color = {r=0.2, g=0.9, b=0.2},
		max_temperature = 100,
		icon = "__bot365-nuclear-fuel-reprocessing__/graphics/icons/uranium_process/pu-aqua.png",
		icon_size = 32,
		pressure_to_speed_ratio = 0.4,
		flow_to_energy_ratio = 0.59,
		order = "a[fluid]-u[pu-aqueous]"
	},
	{
		type = "fluid",
		name = "u-tbp-aqueous",
		subgroup = "uranium-prefluids",
		default_temperature = 25,
		heat_capacity = "1KJ",
		base_color = {r=0.43, g=1, b=0.61},
		flow_color = {r=1, g=0.1, b=0.3},
		max_temperature = 100,
		icon = "__bot365-nuclear-fuel-reprocessing__/graphics/icons/uranium_process/UTPB-aqua.png",
		icon_size = 32,
		pressure_to_speed_ratio = 0.4,
		flow_to_energy_ratio = 0.59,
		order = "a[fluid]-v[u-tbp-aqueous]"
	},
	{
		type = "fluid",
		name = "u-aqueous",
		subgroup = "uranium-prefluids",
		default_temperature = 25,
		heat_capacity = "1KJ",
		base_color = {r=0.43, g=1, b=0.61},
		flow_color = {r=1, g=0.1, b=0.3},
		max_temperature = 100,
		icon = "__bot365-nuclear-fuel-reprocessing__/graphics/icons/uranium_process/u-aqua.png",
		icon_size = 32,
		pressure_to_speed_ratio = 0.4,
		flow_to_energy_ratio = 0.59,
		order = "a[fluid]-w[u-aqueous]"
	},
	{
		type = "fluid",
		name = "waste-tbp",
		subgroup = "uranium-prefluids",
		default_temperature = 25,
		heat_capacity = "1KJ",
		base_color = {r=0, g=0.17, b=0.4},
		flow_color = {r=0.4, g=0.4, b=0.4},
		max_temperature = 100,
		icon = "__bot365-nuclear-fuel-reprocessing__/graphics/icons/uranium_process/waste-TBP.png",
		icon_size = 32,
		pressure_to_speed_ratio = 0.4,
		flow_to_energy_ratio = 0.59,
		order = "a[fluid]-x[waste-tbp]"
	},
	{
		type = "fluid",
		name = "pu(iv)-aqueous",
		subgroup = "uranium-prefluids",
		default_temperature = 25,
		heat_capacity = "1KJ",
		base_color = {r=1, g=0.2, b=0.71},
		flow_color = {r=1, g=1, b=1},
		max_temperature = 100,
		icon = "__bot365-nuclear-fuel-reprocessing__/graphics/icons/uranium_process/pu-aqua-IV.png",
		icon_size = 32,
		pressure_to_speed_ratio = 0.4,
		flow_to_energy_ratio = 0.59,
		order = "a[fluid]-y[pu(iv)-aqueous]"
	},
	{
		type = "fluid",
		name = "pu(iv)-tbp",
		subgroup = "uranium-prefluids",
		default_temperature = 25,
		heat_capacity = "1KJ",
		base_color = {r=1, g=0.2, b=0.71},
		flow_color = {r=1, g=1, b=1},
		max_temperature = 100,
		icon = "__bot365-nuclear-fuel-reprocessing__/graphics/icons/uranium_process/pu-tbp-IV.png",
		icon_size = 32,
		pressure_to_speed_ratio = 0.4,
		flow_to_energy_ratio = 0.59,
		order = "a[fluid]-z[pu(iv)-tbp]"
	},
	{
		type = "fluid",
		name = "waste-complex",
		subgroup = "uranium-prefluids",
		default_temperature = 25,
		heat_capacity = "1KJ",
		base_color = {r=0.2, g=0.2, b=0.2},
		flow_color = {r=0.8, g=0.8, b=0.8},
		max_temperature = 100,
		icon = "__bot365-nuclear-fuel-reprocessing__/graphics/icons/uranium_process/waste-complex.png",
		icon_size = 32,
		pressure_to_speed_ratio = 0.4,
		flow_to_energy_ratio = 0.59,
		order = "a[fluid]-za[waste-complex]"
	},
	{
		type = "fluid",
		name = "recovered-nitric-acid",
		subgroup = "uranium-prefluids",
		default_temperature = 25,
		heat_capacity = "1KJ",
		base_color = {r=0, g=0.34, b=0.6},
		flow_color = {r=0.7, g=0.7, b=0},
		max_temperature = 100,
		icon = "__bot365-nuclear-fuel-reprocessing__/graphics/icons/uranium_process/recovered-nitric-acid.png",
		icon_size = 32,
		pressure_to_speed_ratio = 0.4,
		flow_to_energy_ratio = 0.59,
		order = "a[fluid]-zb[recovered-nitric-acid]"
	},
	{
		type = "fluid",
		name = "waste",
		subgroup = "uranium-prefluids",
		default_temperature = 25,
		heat_capacity = "1KJ",
		base_color = {r=0, g=0, b=0},
		flow_color = {r=1, g=0.2, b=0.2},
		max_temperature = 100,
		icon = "__bot365-nuclear-fuel-reprocessing__/graphics/icons/uranium_process/waste.png",
		icon_size = 32,
		pressure_to_speed_ratio = 0.4,
		flow_to_energy_ratio = 0.59,
		order = "a[fluid]-zc[waste]"
	},
	{
    	type = "fluid",
		name = "Phosphoryl-chloride",
		subgroup = "uranium-prefluids",
		default_temperature = 25,
		heat_capacity = "1KJ",
		base_color = {r=0.78, g=0.93, b=0.16}, --201, 237, 42
		flow_color = {r=0.69, g=0.82, b=0.16}, --177, 209, 39
		max_temperature = 100,
    	icon = "__bot365-nuclear-fuel-reprocessing__/graphics/icons/uranium_process/Phosphoryl-chloride.png",
    	icon_size = 32,
		pressure_to_speed_ratio = 0.4,
		flow_to_energy_ratio = 0.59,
		order = "a[fluid]-zd"
    },
    {
        type = "fluid",
        name = "Tributyl-phosphate",
        subgroup = "uranium-prefluids",
	    default_temperature = 25,
	    heat_capacity = "1KJ",
	    base_color = {r=0.8, g=0.8, b=0.8},
	    flow_color = {r=0.3, g=0.3, b=0.3},
	    max_temperature = 100,
        icon = "__bot365-nuclear-fuel-reprocessing__/graphics/icons/uranium_process/TBP.png",
        icon_size = 32,
	    pressure_to_speed_ratio = 0.4,
	    flow_to_energy_ratio = 0.59,
	    order = "a[fluid]-ze[Tributyl-phosphate]"
	},
	{
		type ="fluid",
		name = "butanol",
		subgroup = "uranium-prefluids",
		default_temperature = 25,
	    heat_capacity = "1KJ",
	    base_color = {r=0.1, g=0.1, b=0.1},
	    flow_color = {r=0.15, g=0.15, b=0.15},
	    max_temperature = 100,
        icon = "__bot365-nuclear-fuel-reprocessing__/graphics/icons/uranium_process/butanol.png",
        icon_size = 32,
	    pressure_to_speed_ratio = 0.4,
	    flow_to_energy_ratio = 0.59,
	    order = "a[fluid]-zf"
	},
	{
		type ="fluid",
		name = "Phosphorus-trichloride",
		subgroup = "uranium-prefluids",
		icon = "__bot365-nuclear-fuel-reprocessing__/graphics/icons/uranium_process/Phosphorus-trichloride.png",
        icon_size = 32,
		default_temperature = 25,
	    heat_capacity = "1KJ",
	    base_color = {r=0.52, g=0.96, b=0.13},--132, 224, 33
	    flow_color = {r=0.46, g=0.8, b=0.08},--118, 206, 22
	    max_temperature = 100,
	    pressure_to_speed_ratio = 0.4,
	    flow_to_energy_ratio = 0.59,
	    order = "a[fluid]-zg"
	},
	{
		type="fluid",
		name="uranium-tetra-fluride",
		subgroup = "uranium-prefluids",
		icon="__bot365-nuclear-fuel-reprocessing__/graphics/icons/uranium_process/uranium-tetra-fluoride.png",
		icon_size=32,
		default_temperature = 25,
	    heat_capacity = "1KJ",
	    base_color = {r=0.8, g=0.8, b=0.8},
	    flow_color = {r=0.3, g=0.3, b=0.3},
	    max_temperature = 100,
	    pressure_to_speed_ratio = 0.4,
	    flow_to_energy_ratio = 0.59,
	    order = "a[fluid]-zh"
	}
})